#!/bin/bash
# Aurthor: Muhammad Asim
# Purpose: Backblaze Automated Backups for OS Windows/Linux
# Contact: <quickbooks2018@gmail.com> https://www.youtube.com/c/AWSLinuxWindows


# Put the Directory/File Name in the variable FILENAME
FILENAME="power"
BACKUP="$FILENAME"
DATE=`date +'%d-%m-%Y'`

# Blackblaze Setup
B2_ACC_ID="PUT Your Account ID"
B2_APP_KEY="Put Your KeY"
B2_BUCKET_NAME="Buckey Name"

# Compression Setup, creating a tar
tar -czvf "$BACKUP"."$DATE".tar.gz "$BACKUP"

# Local Retention Setup
IGNORE_1=`ls -lthr | tail -n2 | awk '{print $NF}' | head -n1`
IGNORE_2=`ls -lthr | tail -n2 | awk '{print $NF}' | tail -n1`

if [ -d "$PWD/Backblaze" ]
then
echo -e "\nDirectory "$PWD/Backblaze" already exists\n"
else
echo -e "\n Creating a Directory "$PWD/Backblaze" \n"
mkdir $PWD/Backblaze
fi


mv "$BACKUP"."$DATE".tar.gz  $PWD/Backblaze
cd $PWD/Backblaze
ls --ignore="$IGNORE_1" --ignore="$IGNORE_2" | xargs rm -rf

# Upload to Blackblaze
echo "starting upload "$BACKUP"."$DATE".tar.gz to b2 at $(date +'%d-%m-%Y %H:%M:%S')"
b2 authorize-account $B2_ACC_ID $B2_APP_KEY
b2 upload_file $B2_BUCKET_NAME "$BACKUP"."$DATE".tar.gz "$BACKUP"."$DATE".tar.gz
echo "finished uploading "$BACKUP"."$DATE".tar.gz to b2 at $(date +'%d-%m-%Y %H:%M:%S')"
exit 0

#END

# ref:https://medium.com/@aslamhadi/daily-backup-database-to-backblaze-cloud-storage-f6659d0e2f53
# ref: https://www.youtube.com/watch?v=GOkAy2RqRQk


# Installations
https://chocolatey.org/docs/installation
Powershell command ---> run as administrator

Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))


choco install python  ---> (5 Times Yes)


https://www.backblaze.com/b2/docs/quick_command_line.html
pip install --upgrade --ignore-installed b2


# Git Bash Setup
https://git-scm.com/downloads

# Git Bash Task Schedular Setup
"C:\Program Files\Git\git-bash.exe"
--cd-to-home /c/Users/Administrator/Desktop/backup.sh


# Best open source tool is Cyberduck 
https://cyberduck.io/


